
export const Technologies = [
    "js",
    "jvm",
    "llvm",
    "scala",
    ".net",
    "A-frame",
    "Advanced data structures",
    "Aerogear",
    "Ai",
    "Airflow",
    "Ajax",
    "Akka",
    "Android",
    "Android/ios",
    "Angular",
    "Angular.js",
    "Angularjs",
    "Ansible",
    "Antlr",
    "Apache airflow",
    "Apache arrow",
    "Apache beam",
    "Apache kafka",
    "Apache spark",
    "Api",
    "Apis",
    "App",
    "Archc",
    "Arduino",
    "Arm",
    "Arrow",
    "Artificial intelligence",
    "Asciidoctor",
    "Asic",
    "Asm",
    "Asm/c/c++",
    "Asr",
    "Assembler",
    "Assembly",
    "Assembly language",
    "Asyncapi",
    "Asynchronous i/o",
    "Atom",
    "Audio",
    "Audio procesing",
    "Audio processing",
    "Automated reasoning",
    "Automaton",
    "Automotive",
    "Autotools",
    "Awk",
    "Aws",
    "Babel",
    "Backend",
    "Bash",
    "Batman",
    "Bazel",
    "Beacon",
    "Beacons",
    "Beaglebone",
    "Beam",
    "Bibtex",
    "Big data",
    "Big data science",
    "Bigquery",
    "Bioinformatics",
    "Biojs",
    "Bios",
    "Bison",
    "Blender",
    "Blockchain",
    "Bluetooth",
    "Boinc",
    "Boost",
    "Bootstrap",
    "Bpm",
    "Breakpad",
    "Browser extension",
    "Browser extensions",
    "Bsd",
    "Bsd make",
    "Bsd unix",
    "Buildbot",
    "Bundler",
    "Bytecode",
    "C",
    "C language",
    "C programming",
    "C#",
    "C++",
    "C++ libraries c++11 c++14 c++17 c++20",
    "C++ template metaprogramming",
    "C++11",
    "C++14",
    "C++17",
    "C++17 parallel stl",
    "C++20",
    "C/c+",
    "C/rust/go",
    "C99",
    "Cabal",
    "Cad",
    "Caffe",
    "Cakephp",
    "Canvas",
    "Cassandra",
    "Celery",
    "Ceph",
    "Cesium",
    "Cesiumjs",
    "Chapel",
    "Chatbots",
    "Che",
    "Chisel",
    "Chromium",
    "Ci",
    "Ci/cd",
    "Cifs",
    "Clang",
    "Clojure",
    "Clojurescript",
    "Cloud",
    "Cmake",
    "Cms",
    "Cocoa",
    "Codec",
    "Codecs",
    "Codeworld",
    "Colab",
    "Communication protocol",
    "Compiler",
    "Compilers",
    "Component-based development",
    "Compression",
    "Computer vision",
    "Concurrency",
    "Configuration management",
    "Container orchestration",
    "Containers",
    "Content management system",
    "Coq",
    "Couchdb",
    "Cpp",
    "Cross-platform",
    "Crossplatform",
    "Cryptography",
    "Css",
    "Css3",
    "Cuda",
    "Cups",
    "Cypress",
    "Cython",
    "C\u00e9u",
    "D",
    "D3",
    "D3.js",
    "D3js",
    "Dart",
    "Dart/flutter",
    "Dash",
    "Dask",
    "Data",
    "Data analysis",
    "Data science",
    "Data structures",
    "Data-science",
    "Database",
    "Databases",
    "Datproject",
    "Ddos",
    "Decentralisation",
    "Decode",
    "Deep learning",
    "Deeplearning",
    "Devops",
    "Dhcp",
    "Dicom",
    "Differential privacy",
    "Directx",
    "Distributed computing",
    "Distributed key-value store",
    "Distributed systems",
    "Django",
    "Django+postgresql",
    "Dlang",
    "Dns",
    "Docker",
    "Documentation",
    "Dpdk",
    "Drm",
    "Drones",
    "Drupal",
    "Drupal 8",
    "Dsp",
    "Dtrace",
    "Ebpf",
    "Eclipse",
    "Eclipsejavaide",
    "Eiffel",
    "Elasicsearch",
    "Elasticsearch",
    "Electromobility",
    "Electron",
    "Elixir",
    "Elk",
    "Elm",
    "Email",
    "Embedded",
    "Embedded systems",
    "Ember",
    "Emberjs",
    "Emscripten",
    "Encode",
    "Envoy",
    "Epbf",
    "Erlang",
    "Espresso",
    "Euslisp",
    "Event-loop",
    "F#",
    "Fasm",
    "Fast fluid dynamics",
    "Fault tolerant",
    "Federated learning",
    "Ffmpeg",
    "Fhir",
    "Filesystems",
    "Finite-state technologies",
    "Firebase",
    "Firewall",
    "Firmware",
    "Flask",
    "Flat assembler",
    "Flatpak",
    "Fluentd",
    "Flutter",
    "Fonts",
    "Fortran",
    "Fossology",
    "Fpga",
    "Framework",
    "Free/netbsd",
    "Frontend",
    "Fsts",
    "Functional programming",
    "Fuzzing",
    "Game development",
    "Garbage-collection",
    "Gawk",
    "Gazebo",
    "Gcc",
    "Gcp",
    "Gdal",
    "Gdscript",
    "Gegl",
    "Generative ai",
    "Geo",
    "Geospatial",
    "Ghc",
    "Ghidra",
    "Gis",
    "Git",
    "Git/github",
    "Github",
    "Github-actions",
    "Gitops",
    "Glib",
    "Gnss",
    "Gnu autotools",
    "Gnu make",
    "Gnu/linux",
    "Gnupg",
    "Go",
    "Gobject",
    "Golan",
    "Golang",
    "Google app engine",
    "Google cloud",
    "Google earth",
    "Google web toolkit",
    "Gpu",
    "Gradle",
    "Grafana",
    "Graph",
    "Graphics",
    "Graphite",
    "Graphql",
    "Groovy",
    "Grpc",
    "Gstreamer",
    "Gtk",
    "Gtk+",
    "Gtkmm",
    "Gui",
    "Guile",
    "Guix",
    "Gwt",
    "Hadoop",
    "Hardware",
    "Hardware acceleration",
    "Haskell",
    "Hdf5",
    "Helm",
    "Hg",
    "Hibernate",
    "Hid",
    "Hidden markov models",
    "High performance computing",
    "High-resolution timers",
    "Hl7 fhir",
    "Homomorphic encryption",
    "Honeypot",
    "Honeypots",
    "Hpc",
    "Hpx",
    "Htc vive",
    "Html",
    "Html5",
    "Html5 canvas",
    "Html5/css3",
    "Htop",
    "Http/2",
    "Huggingface",
    "Hydra",
    "Hyperledger aries",
    "Hypervisor",
    "I386",
    "I586",
    "Iaccessible2",
    "Ice - zeroc",
    "Ida-pro",
    "Ide",
    "Ignition",
    "Illumos",
    "Imaging",
    "Influxdb",
    "Instrumentation",
    "Integer set library",
    "Internationalization",
    "Internet of things",
    "Ionic",
    "Ios",
    "Iot",
    "Ipp",
    "Irc",
    "Isabelle proof assistant",
    "Isl",
    "Jakarta",
    "Jakartaee",
    "Java",
    "Java ee",
    "Javacc",
    "Javafx",
    "Javasc",
    "Javascr",
    "Javascript",
    "Jax",
    "Jenkins",
    "Jinja2",
    "Jni",
    "Jquery",
    "Jruby",
    "Json",
    "Json api",
    "Json schema",
    "Json/json-ld",
    "Jsonnet",
    "Juce",
    "Juice shop",
    "Julia",
    "Julialang",
    "Junit",
    "Jupyter",
    "Jupyter hub",
    "Jupyter notebook",
    "Jvm",
    "Kafka",
    "Kconfig",
    "Keras",
    "Kernel",
    "Kibana",
    "Kms",
    "Kotlin",
    "Kubernetes",
    "Kubernetes operators",
    "Kustomize",
    "Kvm",
    "Lamp",
    "Language-agnostic",
    "Latex",
    "Leaflet",
    "Lede/openwrt",
    "Lfe",
    "Library",
    "Libusb",
    "Libuv",
    "Libxcam",
    "Linkerd",
    "Linux",
    "Linux distribution",
    "Linux kernel",
    "Lisp",
    "Llm",
    "Llvm",
    "Lua",
    "Luarocks",
    "Lunatik",
    "Lwgjl",
    "Lwjgl",
    "Lxc",
    "Machine learning",
    "Machine learning (ml)",
    "Machinelearning",
    "Macos",
    "Make",
    "Many more",
    "Mapping",
    "Maps api",
    "Mariadb",
    "Materialui",
    "Matlab",
    "Matlab/simulink",
    "Mbed",
    "Media",
    "Mediawiki",
    "Medical imaging",
    "Memory",
    "Mercurial",
    "Mern",
    "Meson",
    "Metadata management",
    "Meteor.js",
    "Meteorjs",
    "Micro-services",
    "Micropython",
    "Microservices",
    "Middleware",
    "Midi",
    "Milp",
    "Mips",
    "Ml",
    "Mlir",
    "Mobil",
    "Mobile",
    "Models",
    "Mongo",
    "Mongodb",
    "Mp4",
    "Mp4box",
    "Mpi",
    "Mqtt",
    "Multi-core",
    "Multi-threading",
    "Multimedia",
    "Multimodal analysis",
    "Multimodel ai",
    "Multiplatform",
    "Music",
    "Mysql",
    "Named entity recognition",
    "Namespaces",
    "Natural language processing",
    "Neo4j",
    "Net",
    "Netbsd",
    "Netty",
    "Network stack",
    "Networking",
    "Nextflow",
    "Nextjs",
    "Nix",
    "Nlp",
    "Nltk",
    "Node.js",
    "Nosql",
    "Nss",
    "Nt",
    "Numba",
    "Numpy",
    "Oauth",
    "Object-oriented",
    "Object-storage",
    "Objective c",
    "Ocaml",
    "Ocean science",
    "Ocean technology",
    "Ogc standards",
    "Oidc",
    "Olsr",
    "Ontologies",
    "Open hardware",
    "Open source databases",
    "Open-rmf",
    "Open-sound-control",
    "Openapi",
    "Opencascade",
    "Opencl",
    "Opencv",
    "Opengl",
    "Openhrp",
    "Openinventor",
    "Openj9",
    "Openmp",
    "Openpgp",
    "Openrtm",
    "Openscenegraph",
    "Openstreetmap",
    "Opentelemetry",
    "Opentracing",
    "Opentype",
    "Openvpn",
    "Openwrt",
    "Openxr",
    "Openzfs",
    "Operating systems",
    "Operator",
    "Ordbms",
    "Ortelius",
    "Os",
    "Osx",
    "Pallene",
    "Pandas",
    "Parallel algorithms",
    "Parallel processing",
    "Parallelization",
    "Parsers & compilers",
    "Patroni",
    "Pcap",
    "Pci",
    "Pcl",
    "Pencil",
    "Perl",
    "Perl5",
    "Perl6",
    "Pharo",
    "Php",
    "Physical computing",
    "Physical web",
    "Phyton",
    "Pixhawk",
    "Polly",
    "Polymath",
    "Polymer",
    "Posix",
    "Posix shell",
    "Postgis",
    "Postgres",
    "Postgresql",
    "Ppcg",
    "Processor",
    "Programming languages",
    "Programming-language",
    "Prolog",
    "Prometheus",
    "Protobuf",
    "Protocol buffers",
    "Pthon",
    "Pygame",
    "Pyqt",
    "Pyth",
    "Python",
    "Python 3",
    "Python deep learning frameworks",
    "Python gtk",
    "Pytorch",
    "Qemu",
    "Qml",
    "Qt",
    "Qt5",
    "R",
    "R-project",
    "Rails",
    "Raml",
    "Raspberry pi",
    "Rdbms",
    "Rdf",
    "React",
    "React native",
    "React-native",
    "React.js",
    "Reactive",
    "Reactive extensions",
    "Reactjs",
    "Reactjs javascript",
    "Reactnative",
    "Real-time",
    "Recursive-descent",
    "Redis",
    "Redux",
    "Regular expressions",
    "Remote access",
    "Rest",
    "Rest api",
    "Restful api",
    "Rf",
    "Rfcs",
    "Risc-v",
    "Riscv",
    "Roassal",
    "Robotics",
    "Rom",
    "Ros",
    "Ros/gazebo",
    "Routing",
    "Rpc",
    "Rpm",
    "Rspec",
    "Rtos",
    "Ruby",
    "Ruby on rail",
    "Ruby on rails",
    "Rubygems",
    "Rust",
    "Rxjava",
    "Sanitizers",
    "Sbom",
    "Scala",
    "Scala native",
    "Scala.js",
    "Scalability",
    "Scheme",
    "Science",
    "Scientific python",
    "Scikit-learn",
    "Scilab",
    "Screwdriver",
    "Screwdriver.cd",
    "Scripting",
    "Scss",
    "Sdl",
    "Sdr",
    "Search",
    "Secure multi-party computation",
    "Security",
    "Selenium",
    "Semantic web",
    "Servant",
    "Server",
    "Serverless",
    "Service mesh",
    "Shell",
    "Shell script",
    "Simd",
    "Singularity",
    "Sip",
    "Skala",
    "Smalltalk",
    "Smb",
    "Smt",
    "Smt solvers",
    "Soa",
    "Sockets",
    "Software defined radio",
    "Software radio",
    "Solr",
    "Some/ip",
    "Sound open firmware",
    "Space applications",
    "Spark",
    "Sparql",
    "Spec",
    "Sphinx",
    "Spi",
    "Spinnaker",
    "Spir-v",
    "Spring",
    "Sql",
    "Sql/nosql",
    "Sqlalchemy",
    "Sqlite",
    "Squeak",
    "Ssh",
    "Stable diffusion",
    "Standards",
    "Static analysis",
    "Statistics",
    "Streaming",
    "Subtitles",
    "Sunit",
    "Supercollider",
    "Svelte",
    "Svg",
    "Swift",
    "Swig",
    "Symfony",
    "Syntaxnet",
    "Synthesis",
    "Sysstat",
    "Systemonchip",
    "Systemverilog",
    "Tcl",
    "Tcl/tk",
    "Tcp",
    "Technical writing",
    "Tekton",
    "Templates",
    "Tensorflow",
    "Terminal-kit",
    "Terraform",
    "Testing",
    "Text mining",
    "Textual",
    "Tla+",
    "Tls",
    "Tokio_rs",
    "Torch",
    "Twig",
    "Twisted",
    "Typescript",
    "Uefi",
    "Ui automation",
    "Ui/ux",
    "Unicode",
    "Unix",
    "Unreal engine",
    "V4l2",
    "Va-api",
    "Vaapi",
    "Vala",
    "Vectors",
    "Vega",
    "Vega-lite",
    "Velocity",
    "Verilog",
    "Vhdl",
    "Video",
    "Video codecs",
    "Vim",
    "Virtualization",
    "Virtuoso",
    "Vision",
    "Visual studio",
    "Visualization",
    "Vlsi",
    "Voctomix",
    "Vpp",
    "Vst",
    "Vtk",
    "Vue",
    "Vue.js",
    "Vuejs",
    "Vulkan",
    "Waf",
    "Wayland",
    "Web",
    "Web application firewall",
    "Web apps",
    "Web bluetooth",
    "Web development",
    "Web services",
    "Webassembly",
    "Webasssembly",
    "Webcomponents",
    "Webdriver",
    "Webgl",
    "Webgpu",
    "Webkit",
    "Webpack",
    "Webrtc",
    "Webs",
    "Wiki",
    "Win32",
    "Win32 api",
    "Windows",
    "Wordpress",
    "Workflows",
    "Wxwidgets",
    "X11",
    "X86",
    "X86 assembly",
    "Xarray",
    "Xcode",
    "Xen",
    "Xia",
    "Xilinx",
    "Xml",
    "Xmpp",
    "Xpath",
    "Xr",
    "Xtext",
    "Yaml",
    "Yocto",
    "Zap",
    "Zephyr rtos",
    "Zeroc ice",
    "Zeromq",
    "Zfs",
    "Zig",
    "Zmq",
    "Zope"
  ]
